### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bcrhbrhcdb** [05Konz/Blooket-Cheats#26]
So theres a React and Normal Gui and a .min GUI. WHats the differnece? WHich one should i use? (Sorry im lazy to fix typos lol)

**Comment by 05Konz** [comment]
The React GUI is something Jod made to get around every anti-cheat measure Blooket made, the mobile GUI was the first GUI he ever made, and the normal GUI is just the normal GUI. Any script ending in .min.js is minified meaning it's condensed to be shorter than the normal huge scripts and is intended to be used for making bookmarklets. I would recommend the React GUI since it's the newest and more well made.

**Comment by Shploop** [comment]
I never knew that
