### ISSUE TITLE
wont open the gui

### ISSUE THREAD

**Issue by bigglejits** [05Konz/Blooket-Cheats#47]
### Script

gui.js

### Problem

i copy the GUI put it in my bookmarks and it doesn't run. I do the javascript:code thingy but it wont open the GUI pls help.

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated, Obfuscated

**Comment by victini-fan** [comment]
I have the same problem
I am not on a school Chromebook but I am on a Chromebook
yes shploop I have tried your mobile method

**Comment by Piecrafty** [comment]
i have a problem with using it on scool chombook is it even possible??

**Comment by 14Codes** [comment]
I am coding my on cheats rn, & it seems to be fully blocked. So right now there is now fix. Until he learns about the issue I will try to alert him, My hacks are having the same issue even on a private client.

**Comment by ASTHEBEST** [comment]
did yall try it with the .min files?

**Comment by ASTHEBEST** [comment]
also https://github.com/05Konz/Blooket-Cheats/issues/39#issuecomment-1773955958

**Comment by ASTHEBEST** [comment]
> #39 (comment)
If you're on a school computer javascript is probably blocked, if not how exactly are you running the gui?\

**Comment by 14Codes** [comment]
Yeah, javascript is blocked by most schools but you can unblock it pretty quick dependingon what blocking agent your school uses, Because they don't block your blocking agent from you acessing it so you can chance the settings.  You can unblock java like this. Start the Chrome browser and open chrome://flags. Next, search for “enable developer mode” and enable it. Now, search for “allow all sites to run JavaScript” and enable it.

**Comment by 14Codes** [comment]
for most blocking agents that works

**Comment by 05Konz** [comment]
this is an issue with school devices, not really anything I can do about it

**Comment by 14Codes** [comment]
yeah, i have been working on a bypass. It seems to be very hard to create

**Comment by 14Codes** [comment]
not even sure if its possible
