### ISSUE TITLE
BUG: nothing works

### ISSUE THREAD

**Issue by 110-141-143-153-145-162** [05Konz/Blooket-Cheats#7]
### Script

.

### Problem

.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by src-ry** [comment]
device? browser? browser version?

**Comment by pazza2234** [comment]
Try to go to chrome://policy and if it is blocked you cant check but if it is unblocked look for the section for URLBlocklist. This list is either going to be Exstreamly long, just include javascript; (or any of the following: javascript://, javascript:*, javascript://* all of these work) or nothing will be there. if it is long look for javascript in the block list. if you find it javascript is blocked. if not it is blocked via a different method (or javascript is not enabled but that would break way to much so that is probably not it) But if it is it can be removed via pollon by murkury workshop. Though if you have to return your chromebook would not recommend doing this.

**Comment by 05Konz** [comment]
likely a device issue if on a school computer
