### ISSUE TITLE
IDEA: Set points

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#76]
### Gamemode

Classic

### Function

Sets number of points in classic 

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by TheDarknessSurroundsYou** [comment]
sounds cool

**Comment by 05Konz** [comment]
Stored on the host's end

**Comment by Githubman6996** [comment]
> Stored on the host's end

Wouldn’t it be basically the same as  the set (Name) Scripts 

how’s  it not possible

**Comment by Mazedotexe** [comment]
> > Stored on the host's end
> 
> Wouldn’t it be basically the same as the set (Name) Scripts
> 
> how’s it not possible

people on this repo are just so dumb like do you not know what that means 🤦

actually, you probably don't. so let me break it down for you. the reason these cheats WORK is because blooket stores variables with important values on the user's end. which means, somewhere in the code, there is a variable of how much gold in gold quest you have or whatever. so blooket is storing the amount of gold you have on YOUR computer. no one elses. so if your computer randomly told it to change that, the code wouldn't question it, it's code, so it'll make the change.   normally, this isn't too much of a problem, though,  because you can't just change these variables inside of blooket; there isn't some admin panel that ben left in blooket that lets you change what your computer thinks is right (the variable's storage). so how do you change the variables? well, you use JavaScript. JavaScript is basically the holy grail of websites. it can do pretty much anything. using javascript, it's really easy to just find the variable that holds your gold or whatever and change it. and thats exactly what (most of) the cheats in this repository do. they find the variable holding an important value, and just change it. so now you may be wondering: why is setting points impossible, when you can set all these other things? so let me tell you the answer. basically, the amount of points in classic mode is stored in a different way then crypto in cryptohack, or whatever currency it is. the difference is that while the other variables are only on YOUR computer , making them vulnerable to JavaScript being able to change them, classic points (and blooket coins, and other stuff) are stored on your computer AND the teacher's computer. so if you did try to change the amount of points you had, the game would try to change it, but then it would be like "hold up, somethings wrong. the player just said he got a ton of points, but the host doesn't say he got any. since the host is the one... hosting the game, we'll just keep it at what it's at." now, if you could just run scripts on your teacher's computer, this would be totally possible. you could just make your teacher's computer also say you earned a bunch of points. But since you probably won't be running scripts on your teachers computer mid-blooket-game any time soon, its safe to say that you can't change how many points you have on classic blooket.


i hope you read all that and learned instead of just skipping to the bottom, because you sure need it.

**Comment by Githubman6996** [comment]
> > > Stored on the host's end
> 
> > 
> 
> > Wouldn’t it be basically the same as the set (Name) Scripts
> 
> > 
> 
> > how’s it not possible
> 
> 
> 
> people on this repo are just so dumb like do you not know what that means 🤦
> 
> 
> 
> actually, you probably don't. so let me break it down for you. the reason these cheats WORK is because blooket stores variables with important values on the user's end. which means, somewhere in the code, there is a variable of how much gold in gold quest you have or whatever. so blooket is storing the amount of gold you have on YOUR computer. no one elses. so if your computer randomly told it to change that, the code wouldn't question it, it's code, so it'll make the change.   normally, this isn't too much of a problem, though,  because you can't just change these variables inside of blooket; there isn't some admin panel that ben left in blooket that lets you change what your computer thinks is right (the variable's storage). so how do you change the variables? well, you use JavaScript. JavaScript is basically the holy grail of websites. it can do pretty much anything. using javascript, it's really easy to just find the variable that holds your gold or whatever and change it. and thats exactly what (most of) the cheats in this repository do. they find the variable holding an important value, and just change it. so now you may be wondering: why is setting points impossible, when you can set all these other things? so let me tell you the answer. basically, the amount of points in classic mode is stored in a different way then crypto in cryptohack, or whatever currency it is. the difference is that while the other variables are only on YOUR computer , making them vulnerable to JavaScript being able to change them, classic points (and blooket coins, and other stuff) are stored on your computer AND the teacher's computer. so if you did try to change the amount of points you had, the game would try to change it, but then it would be like "hold up, somethings wrong. the player just said he got a ton of points, but the host doesn't say he got any. since the host is the one... hosting the game, we'll just keep it at what it's at." now, if you could just run scripts on your teacher's computer, this would be totally possible. you could just make your teacher's computer also say you earned a bunch of points. But since you probably won't be running scripts on your teachers computer mid-blooket-game any time soon, its safe to say that you can't change how many points you have on classic blooket.
> 
> 
> 
> 
> 
> i hope you read all that and learned instead of just skipping to the bottom, because you sure need it.

Ah ok
