### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#77]

**Comment by Githubman6996** [comment]
Would have a limit of the max lives for a game hosted

**Comment by ASTHEBEST** [comment]
Did you really read the whole dropdown thing? under "Can you make more battle royale cheats" it says
Battle Royale is a gamemode that works almost entirely on the host's end. The only thing we have control over is answering questions.

**Comment by Githubman6996** [comment]
Yeah I read it

**Comment by Mazedotexe** [comment]
> Yeah I read it

and you didnt see the giant text that says "Can you make more battle royale cheats? No, it's mostly on the host's side.". also, it seems you didn't even properly read the thing you replied to, because all but one sentence is why this issue shouldn't exist and proof that "I have read the FaQ and my suggestion has not already been asked for or isn't possible" is false. so why is this still up? skid and a liar🤦
